version: 2
jobs:
  build:
    working_directory: ~/ta
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running linter
          command: |
            . venv/bin/activate
            pycodestyle --max-line-length=119 ta && isort --check-only --recursive ta
      - run:
          name: Running test
          command: |
            . venv/bin/activate
            python -m unittest discover
      - store_test_results:
          path: test-results
